#pragma once

#include "resources/blip.h"
#include "resources/coin.h"
#include "resources/copyright.h"
#include "resources/explosion.h"
#include "resources/gameover.h"
#include "resources/hit.h"
#include "resources/houseloop.h"
#include "resources/laser.h"
#include "resources/numbers.h"
#include "resources/pressenter.h"
#include "resources/pressspace.h"
#include "resources/quit.h"
#include "resources/return.h"
#include "resources/score.h"
#include "resources/version.h"
